theme: jekyll-theme-slate

url: "http://docs.artsdata.ca" 
baseurl: ""                     

collections:
  classes:
    output: true
  architecture:
    output: true
  gabarits-jsonld:
    output: true

# --- Include CNAME file in the built site (important) ---
include:
  - CNAME
